/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CF.ConversorTemperatura;

import CF.EscolhaProjeto.telaEscolhaProjeto;
import javax.swing.ImageIcon;

/**
 *
 * @author José Satiro
 */
public class telaConversorTemperatura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(telaConversorTemperatura.class.getName());

    /**
     * Creates new form telaConversorTemperatura
     */
    
    boolean temaEscuro = true;
    
    public telaConversorTemperatura() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        aplicarTema();
    }
    
    private void aplicarTema() {
        if (temaEscuro) {
            jPanel1.setBackground(new java.awt.Color(30, 30, 30));
            
            CONVETER.setBackground(new java.awt.Color(18, 0, 63));
            
            tituloTela.setForeground(new java.awt.Color(255, 255, 255));
            
            subTituloTela.setForeground(new java.awt.Color(255, 255, 255));
            
            imgTermometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/termometro (3).png"))); // NOI18N
            
            de.setForeground(new java.awt.Color(255, 255, 255));
            
            linhaMeioUm.setBackground(new java.awt.Color(255, 255, 255));
            linhaMeioUm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            
            linhaMeioDois.setBackground(new java.awt.Color(255, 255, 255));
            linhaMeioDois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
            
            imgSetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/reverter-setas-desenhadas-a-mao.png")));
            
            para.setForeground(new java.awt.Color(255, 255, 255));
            
            returnBotao.setBackground(new java.awt.Color(30, 30, 30));
            returnBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/voltar.png"))); // NOI18N
            
            temaBotao.setBackground(new java.awt.Color(30, 30, 30));
            temaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/brilho-do-sol.png"))); // NOI18N
            
            
        } else {
            jPanel1.setBackground(new java.awt.Color(242, 238, 249));
            
            CONVETER.setForeground(new java.awt.Color(255, 255, 255));
            
            tituloTela.setForeground(new java.awt.Color(0, 0, 0));
            
            subTituloTela.setForeground(new java.awt.Color(0, 0, 0));
            
            imgTermometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/termometro (4).png"))); // NOI18N
            
            de.setForeground(new java.awt.Color(0, 0, 0));
            
            linhaMeioUm.setBackground(new java.awt.Color(0, 0, 0));
            linhaMeioUm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            
            linhaMeioDois.setBackground(new java.awt.Color(255, 255, 255));
            linhaMeioDois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
            
            imgSetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/reverter-setas-desenhadas-a-mao (1).png")));
            
            para.setForeground(new java.awt.Color(0, 0, 0));
            
            returnBotao.setBackground(new java.awt.Color(242, 238, 249));
            returnBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/voltar (1).png"))); // NOI18N
            
            temaBotao.setBackground(new java.awt.Color(242, 238, 249));
            temaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/moon (1).png"))); // NOI18N
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        botaoLimpar = new javax.swing.JButton();
        CONVETER = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        tituloTela = new javax.swing.JLabel();
        subTituloTela = new javax.swing.JLabel();
        imgTermometro = new javax.swing.JLabel();
        de = new javax.swing.JLabel();
        linhaMeioUm = new javax.swing.JPanel();
        linhaMeioDois = new javax.swing.JPanel();
        imgSetas = new javax.swing.JLabel();
        para = new javax.swing.JLabel();
        returnBotao = new javax.swing.JButton();
        temaBotao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor de Temperatura");
        setIconImage(new ImageIcon(getClass().getResource("/icons/logo.png")).getImage());

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        botaoLimpar.setBackground(new java.awt.Color(255, 255, 255));
        botaoLimpar.setForeground(new java.awt.Color(0, 0, 0));
        botaoLimpar.setText("LIMPAR");
        botaoLimpar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        botaoLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        CONVETER.setBackground(new java.awt.Color(124, 77, 255));
        CONVETER.setForeground(new java.awt.Color(255, 255, 255));
        CONVETER.setText("CONVERTER");
        CONVETER.setBorder(null);
        CONVETER.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CONVETER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONVETERActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Celsius", "Fahrenheit", "Kelvin" }));
        jComboBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        tituloTela.setFont(new java.awt.Font("Consolas", 0, 24)); // NOI18N
        tituloTela.setText("Conversor de Temperaturas");

        subTituloTela.setFont(new java.awt.Font("Consolas", 1, 12)); // NOI18N
        subTituloTela.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        subTituloTela.setText("Converta facilmente entre Celsius, Fahrenheit e Kelvin");

        imgTermometro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/termometro (4).png"))); // NOI18N

        de.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        de.setText("De:");

        linhaMeioUm.setBackground(new java.awt.Color(0, 0, 0));
        linhaMeioUm.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout linhaMeioUmLayout = new javax.swing.GroupLayout(linhaMeioUm);
        linhaMeioUm.setLayout(linhaMeioUmLayout);
        linhaMeioUmLayout.setHorizontalGroup(
            linhaMeioUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linhaMeioUmLayout.setVerticalGroup(
            linhaMeioUmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        linhaMeioDois.setBackground(new java.awt.Color(255, 255, 255));
        linhaMeioDois.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout linhaMeioDoisLayout = new javax.swing.GroupLayout(linhaMeioDois);
        linhaMeioDois.setLayout(linhaMeioDoisLayout);
        linhaMeioDoisLayout.setHorizontalGroup(
            linhaMeioDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        linhaMeioDoisLayout.setVerticalGroup(
            linhaMeioDoisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        imgSetas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/reverter-setas-desenhadas-a-mao (1).png"))); // NOI18N

        para.setFont(new java.awt.Font("Consolas", 0, 22)); // NOI18N
        para.setText("Para:");

        returnBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/voltar (1).png"))); // NOI18N
        returnBotao.setBorder(null);
        returnBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBotaoActionPerformed(evt);
            }
        });

        temaBotao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONS/moon (1).png"))); // NOI18N
        temaBotao.setBorder(null);
        temaBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temaBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(para)
                    .addComponent(de)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CONVETER, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBox1, 0, 150, Short.MAX_VALUE)
                                    .addComponent(linhaMeioUm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(imgSetas)
                                        .addGap(18, 18, 18)
                                        .addComponent(linhaMeioDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(tituloTela)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(subTituloTela, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(returnBotao)
                .addGap(115, 115, 115)
                .addComponent(imgTermometro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(temaBotao)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgTermometro)
                    .addComponent(returnBotao)
                    .addComponent(temaBotao))
                .addGap(18, 18, 18)
                .addComponent(tituloTela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(subTituloTela, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(de)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(linhaMeioUm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(linhaMeioDois, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(imgSetas)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(para, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CONVETER, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
        jTextField2.setText("");
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void CONVETERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONVETERActionPerformed
        // TODO add your handling code here:
        String origem = (String) jComboBox1.getSelectedItem();
        String destino = (String) jComboBox2.getSelectedItem();

        double valor = Double.parseDouble(jTextField1.getText());
        double resultado = 0;

        // CONVERSÕES
        if (origem.equals("Celsius") && destino.equals("Fahrenheit")) {
            resultado = valor * 1.8 + 32;
        }
        else if (origem.equals("Celsius") && destino.equals("Kelvin")) {
            resultado = valor + 273.15;
        }
        else if (origem.equals("Celsius") && destino.equals("Celsius")) {
            resultado = valor;
        }

        else if (origem.equals("Fahrenheit") && destino.equals("Celsius")) {
            resultado = (valor - 32) * 5 / 9;
        }
        else if (origem.equals("Fahrenheit") && destino.equals("Kelvin")) {
            resultado = (valor - 32) * 5 / 9 + 273.15;
        }
        else if (origem.equals("Fahrenheit") && destino.equals("Fahrenheit")) {
            resultado = valor;
        }

        else if (origem.equals("Kelvin") && destino.equals("Celsius")) {
            resultado = valor - 273.15;
        }
        else if (origem.equals("Kelvin") && destino.equals("Fahrenheit")) {
            resultado = (valor - 273.15) * 9 / 5 + 32;
        }
        else if (origem.equals("Kelvin") && destino.equals("Kelvin")) {
            resultado = valor;
        }
        jTextField2.setText(String.valueOf(resultado));
    }//GEN-LAST:event_CONVETERActionPerformed

    private void returnBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBotaoActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new telaEscolhaProjeto().setVisible(true);
    }//GEN-LAST:event_returnBotaoActionPerformed

    private void temaBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temaBotaoActionPerformed
        // TODO add your handling code here:
        temaEscuro = !temaEscuro;
        aplicarTema();
    }//GEN-LAST:event_temaBotaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new telaConversorTemperatura().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CONVETER;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JLabel de;
    private javax.swing.JLabel imgSetas;
    private javax.swing.JLabel imgTermometro;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JPanel linhaMeioDois;
    private javax.swing.JPanel linhaMeioUm;
    private javax.swing.JLabel para;
    private javax.swing.JButton returnBotao;
    private javax.swing.JLabel subTituloTela;
    private javax.swing.JButton temaBotao;
    private javax.swing.JLabel tituloTela;
    // End of variables declaration//GEN-END:variables
}
